# api gateway swagger 2.0 yamli vittuilupalvelulle

swagger: '2.0'
info:
  title: vittuilupalvelu-apigateway
  description: voit subscribeä hienoon palveluun
  version: 1.0.0
schemes:
  - https
produces:
  - application/json

paths:
  /sub:
    post:
      summary: subscribee
      operationId: post-subscribe
      x-google-backend:
        # tähän voi kirjoittaa entrypointin muistiin, jos kaikki funktiot samassa filussa
        address: https://us-central1-week9-3.cloudfunctions.net/vittuilupalvelu2
      
      # poista komentti tästä, jos halutaan api-key:
      security:
      - api_key: []
      responses:
        '200':
          description: subscribe onnistui
          schema:
            type: string

# Jos haluaa api-keyn:
securityDefinitions:
  api_key:
    type: "apiKey"
    name: "key"
    in: "query"