# Projekti 3, ryhmä 3: Vittuilu-API
swagger: '2.0'
info:
  title: vittuilu-API
  description: hakee eri vittuilut
  version: 1.0.0
schemes:
  - https
produces:
  - application/json

paths:
  /low:
    get:
      summary: LOW-tierin vittuilut
      operationId: get
      x-google-backend:
        # tähän voi kirjoittaa entrypointin muistiin, jos kaikki funktiot samassa filussa
        address: https://<REGION TÄHÄN>-<PROJEKTI TÄHÄN>.cloudfunctions.net/<FUNKTION NIMI TÄHÄN>
      
      # poista komentti tästä, jos halutaan api-key:
      # security:
      # - api_key: []
      responses:
        '200':
          description: vittuilu ok
          schema:
            type: string

  /medium:
    get:
      summary: MEDIUM-tierin vittuilut
      operationId: get
      x-google-backend:
        # tähän voi kirjoittaa entrypointin muistiin, jos kaikki funktiot samassa filussa
        address: https://<REGION TÄHÄN>-<PROJEKTI TÄHÄN>.cloudfunctions.net/<FUNKTION NIMI TÄHÄN>
      
      # poista komentti tästä, jos halutaan api-key:
      # security:
      # - api_key: []
      responses:
        '200':
          description: vittuilu ok
          schema:
            type: string

  /high:
    get:
      summary: HIGHT-tierin vittuilut
      operationId: get
      x-google-backend:
        # tähän voi kirjoittaa entrypointin muistiin, jos kaikki funktiot samassa filussa
        address: https://<REGION TÄHÄN>-<PROJEKTI TÄHÄN>.cloudfunctions.net/<FUNKTION NIMI TÄHÄN>
      
      # poista komentti tästä, jos halutaan api-key:
      # security:
      # - api_key: []
      responses:
        '200':
          description: vittuilu ok
          schema:
            type: string

# Jos haluaa api-keyn:
# securityDefinitions:
#   api_key:
#     type: "apiKey"
#     name: "key"
#     in: "query"